version: '3.8'

services:
  anti_social:
    image: postgres:latest
    container_name: anti_social
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '5434:5432'
    volumes:
      - ./data/social:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - app-network

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - '5433:5432'
    volumes:
      - ./data/test:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: anti_social_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  api:
    build: .
    deploy:
      replicas: 3
    environment:
      - PORT=3000
      - POSTGRES_HOST=anti_social
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - anti_social
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8081:80'
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
